### ISSUE TITLE
TextField not show

### ISSUE THREAD

**Issue by Lenhulk** [IamSaurav/BMDialPad#1]
Why does TextField not change after clicking on any buttons on the keyboard after initialization? Only when I click TextField, can TextField display and accept the event normally?
Thx.

**Comment by IamSaurav** [comment]
Well with what I understood from your question is that, it works like a phone app of iPhone. If you play around the phone app you can relate.
If you have a specific issue pls elaborate and share a screenshot.

**Comment by navin111** [comment]
how to dismiss BMDialPad

**Comment by IamSaurav** [comment]
@navin111 It's a UIView so you can dismiss by calling, removeFromSuperview(). However you're welcome to contribute to the repo to add dismiss function.
